# Library Import

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statistics as st

# Sciket Learn
from sklearn.linear_model import LogisticRegression as lr, LinearRegression 
from sklearn.preprocessing import StandardScaler as ss, OneHotEncoder as ohe
from sklearn.metrics import classification_report as cr, confusion_matrix as cm, accuracy_score as AS, recall_score as rc, precision_score as ps, f1_score
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split as tts, GridSearchCV as gscv
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.tree import DecisionTreeClassifier as dtc, plot_tree as pt, export_graphviz
from sklearn.neighbors import KNeighborsClassifier as knc
from sklearn.svm import SVC
from sklearn.compose import ColumnTransformer as ct
from sklearn.naive_bayes import MultinomialNB as nb
from sklearn.naive_bayes import GaussianNB as gnb


# Data Import

In [2]:
# Data Importing
dat = pd.read_csv(r"E:\DATA FOR TEST\Tele Customer churn\WA_Fn-UseC_-Telco-Customer-Churn.csv")
dat['TotalCharges'] = pd.to_numeric(dat.TotalCharges, errors = 'coerce')
data = dat.copy()
data['TotalCharges'] = data['TotalCharges'].fillna(data['TotalCharges'].mean())
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes


# EDA

In [3]:

print(data.info())
print(data.describe())
print(data.isnull().sum())

# Drop ID column (FIXED)
data.drop(columns=['customerID'], inplace=True)

# Split Data in X and Y
x = data.iloc[:, :-1]
y = data.iloc[:, -1]

# Train-test split
x_train, x_test, y_train, y_test = tts(x, y, test_size=0.2, random_state = 42)

# Feature Encoding One HOT Encoder
cat_col = x_train.select_dtypes(include=['object', 'category']).columns

one_hot = ct(transformers = [('encoder', ohe(handle_unknown = 'ignore'), cat_col)], remainder = 'passthrough')

x_train_encoded = one_hot.fit_transform(x_train)
x_test_encoded = one_hot.transform(x_test)

# Feature Scaling
scaler = ss()
x_train = scaler.fit_transform(x_train_encoded)
x_test = scaler.transform(x_test_encoded)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


# Machine Learning Model One by One

In [4]:
# Machine Learning logistic Model Initilization
logistic_model = LogisticRegression()
logistic_model.fit(x_train, y_train)
y_pred_logistic_model = logistic_model.predict(x_test)
print("Classification Report :\n", cr(y_test, y_pred_logistic_model))

c_matrics = cm(y_test, y_pred_logistic_model)
print("Confusion Matrix logistic_model:\n", c_matrics)

TN, FP, FN, TP = c_matrics.ravel()
total = TN + FP + FN + TP

print("\nDetails (Counts and Percentages):")
print(f"True Negative (TN): {TN} ({TN/total*100:.2f}%)")
print(f"True Positive (TP): {TP} ({TP/total*100:.2f}%)")
print(f"False Positive (FP): {FP} ({FP/total*100:.2f}%)")
print(f"False Negative (FN): {FN} ({FN/total*100:.2f}%)")


NameError: name 'LogisticRegression' is not defined

In [ ]:
# Machine Learning Support Vector Machine Model Initilization
SVM_model = SVC()
SVM_model.fit(x_train, y_train)
y_pred_SVM_model = SVM_model.predict(x_test)
print("Classification Report SVM_model:\n", cr(y_test, y_pred_SVM_model))

c_matrics = cm(y_test, y_pred_SVM_model)
print("Confusion Matrix :\n", c_matrics)

TN, FP, FN, TP = c_matrics.ravel()
total = TN + FP + FN + TP

print("\nDetails (Counts and Percentages):")
print(f"True Negative (TN): {TN} ({TN/total*100:.2f}%)")
print(f"True Positive (TP): {TP} ({TP/total*100:.2f}%)")
print(f"False Positive (FP): {FP} ({FP/total*100:.2f}%)")
print(f"False Negative (FN): {FN} ({FN/total*100:.2f}%)")


In [ ]:
# Machine Learning k_Neighbours Model Initilization
k_Neighbours_Classifier = knc()
k_Neighbours_Classifier.fit(x_train, y_train)
y_pred_k_Neighbours_Classifier = k_Neighbours_Classifier.predict(x_test)
print("Classification Report :\n", cr(y_test, y_pred_k_Neighbours_Classifier))

c_matrics = cm(y_test, y_pred_k_Neighbours_Classifier)
print("Confusion Matrix k_Neighbours:\n", c_matrics)

TN, FP, FN, TP = c_matrics.ravel()
total = TN + FP + FN + TP

print("\nDetails (Counts and Percentages):")
print(f"True Negative (TN): {TN} ({TN/total*100:.2f}%)")
print(f"True Positive (TP): {TP} ({TP/total*100:.2f}%)")
print(f"False Positive (FP): {FP} ({FP/total*100:.2f}%)")
print(f"False Negative (FN): {FN} ({FN/total*100:.2f}%)")


In [ ]:
# Machine Learning Random Forest Model Initilization
Random_Forest_model = rfc()
Random_Forest_model.fit(x_train, y_train)
y_pred_Random_Forest_model = Random_Forest_model.predict(x_test)
print("Classification Report :\n", cr(y_test, y_pred_Random_Forest_model))

c_matrics = cm(y_test, y_pred_Random_Forest_model)
print("Confusion Matrix Random_Forest_model:\n", c_matrics)

TN, FP, FN, TP = c_matrics.ravel()
total = TN + FP + FN + TP

print("\nDetails (Counts and Percentages):")
print(f"True Negative (TN): {TN} ({TN/total*100:.2f}%)")
print(f"True Positive (TP): {TP} ({TP/total*100:.2f}%)")
print(f"False Positive (FP): {FP} ({FP/total*100:.2f}%)")
print(f"False Negative (FN): {FN} ({FN/total*100:.2f}%)")


In [ ]:
# Machine Learning Decision_Tree_Model Initilization
Decision_Tree_Model = LogisticRegression()
Decision_Tree_Model.fit(x_train, y_train)
y_pred_Decision_Tree_Model = Decision_Tree_Model.predict(x_test)
print("Classification Report Decision_Tree_Model:\n", cr(y_test, y_pred_Decision_Tree_Model))

c_matrics = cm(y_test, y_pred_Decision_Tree_Model)
print("Confusion Matrix :\n", c_matrics)

TN, FP, FN, TP = c_matrics.ravel()
total = TN + FP + FN + TP

print("\nDetails (Counts and Percentages):")
print(f"True Negative (TN): {TN} ({TN/total*100:.2f}%)")
print(f"True Positive (TP): {TP} ({TP/total*100:.2f}%)")
print(f"False Positive (FP): {FP} ({FP/total*100:.2f}%)")
print(f"False Negative (FN): {FN} ({FN/total*100:.2f}%)")


In [ ]:
# Machine Learning Naive Bayes Model Initilization
Multinobials_Naive_bais_Model = LogisticRegression()
Multinobials_Naive_bais_Model.fit(x_train, y_train)
y_pred_Multinobials_Naive_bais_Model = Multinobials_Naive_bais_Model.predict(x_test)
print("Classification Report Multinobials_Naive_bais_Model:\n", cr(y_test, y_pred_Multinobials_Naive_bais_Model))

c_matrics = cm(y_test, y_pred_Multinobials_Naive_bais_Model)
print("Confusion Matrix :\n", c_matrics)

TN, FP, FN, TP = c_matrics.ravel()
total = TN + FP + FN + TP

print("\nDetails (Counts and Percentages):")
print(f"True Negative (TN): {TN} ({TN/total*100:.2f}%)")
print(f"True Positive (TP): {TP} ({TP/total*100:.2f}%)")
print(f"False Positive (FP): {FP} ({FP/total*100:.2f}%)")
print(f"False Negative (FN): {FN} ({FN/total*100:.2f}%)")


# One Function For all Classification Data

In [ ]:
def find_best_model(x, y):

    models = {
        "LogisticRegression": lr(max_iter=1000),
        "RandomForest": rfc(),
        "DecisionTree": dtc(),
        "KNN": knc(),
        "SVC": SVC()
    }

    x_train, x_test, y_train, y_test = tts(
        x, y, test_size=0.2, random_state=42,
        shuffle=True,
        stratify=y
    )

    cat_cols = x.select_dtypes(include=['object', 'category']).columns
    num_cols = x.select_dtypes(include=['int64', 'float64']).columns

    preprocessor = ct(
        transformers=[
            ('encoder', ohe(handle_unknown='ignore'), cat_cols),
            ('scaler', ss(), num_cols)
        ]
    )

    for name, model in models.items():
        print(f"\n===== {name} =====")
        pipe = Pipeline([
            ('prep', preprocessor),
            ('model', model)
        ])

        pipe.fit(x_train, y_train)
        y_pred = pipe.predict(x_test)

        print(cr(y_test, y_pred))

        cmatrix = cm(y_test, y_pred)
        print("Confusion Matrix:\n", cmatrix)
        
        TN, FP, FN, TP = cmatrix.ravel()
        total = TN + FP + FN + TP

        print(f"TN: {TN} ({TN/total*100:.2f}%)")
        print(f"FP: {FP} ({FP/total*100:.2f}%)")
        print(f"FN: {FN} ({FN/total*100:.2f}%)")
        print(f"TP: {TP} ({TP/total*100:.2f}%)")

find_best_model(x, y)


# No Help Code Practice

In [5]:
def find_best_model(x, y):
    models = {'Logistic Regression': lr(),
              'Support Vector Machine': SVC(),
              'Random Forest':rfc(),
              'Decision Tress':dtc(),
              'K Near Neighbour':knc()}

    x_train, x_test, y_train, y_test = tts(x, y, test_size = 0.2, random_state = 42, shuffle = True, stratify = y)

    num_col = x_train.select_dtypes(include=['int64', 'float64']).columns
    cat_col = x_train.select_dtypes(include=['object', 'category']).columns

    prep = ct(transformers = [
        ('encoder', ohe(handle_unknown = 'ignore'), cat_col),
        ('scaler', ss(), num_col) ])

    for name, model in models.items():
        print("="*7, "*"*3, {name}, "*"*3, "="*7)

        pipe = Pipeline([
            ('prep', prep),
            ('model', model) ])

        pipe.fit(x_train, y_train)

        y_pred = pipe.predict(x_test)

        print(f"Classification Report : {name}\n{cr(y_test, y_pred)}") 
        c_matrix = cm(y_test, y_pred)

        TN, FP, FN, TP = c_matrix.ravel()
        print(f"Confusion Matrix {name}\n{c_matrix}\n")
        print(f"True Negative {TN} | {TN/(TN+FP+FN+TP)*100}%")
        print(f"False Positive {FP} | {TP/(TN+FP+FN+TP)*100}%")
        print(f"False Negative {FN} | {FN/(TN+FP+FN+TP)*100}%")
        print(f"True Positive {TP} | {TP/(TN+FP+FN+TP)*100}%")
        print()

find_best_model(x, y)

======= *** {'Logistic Regression'} *** =======
Classification Report : Logistic Regression
              precision    recall  f1-score   support

          No       0.85      0.89      0.87      1035
         Yes       0.66      0.56      0.60       374

    accuracy                           0.81      1409
   macro avg       0.75      0.73      0.74      1409
weighted avg       0.80      0.81      0.80      1409

Confusion Matrix Logistic Regression
[[926 109]
 [165 209]]

True Negative 926 | 65.72036905606812%
False Positive 109 | 14.83321504613201%
False Negative 165 | 11.710432931156848%
True Positive 209 | 14.83321504613201%

======= *** {'Support Vector Machine'} *** =======
Classification Report : Support Vector Machine
              precision    recall  f1-score   support

          No       0.83      0.90      0.86      1035
         Yes       0.64      0.48      0.55       374

    accuracy                           0.79      1409
   macro avg       0.74      0.69      0.71 

In [26]:
def all_model_once(x, y):
    models = {'Logistic Regression': lr(),
              'Support Vector Machine':SVC(),
              'K Near Neighbours':knc(),
              'Random Forest Method':rfc(),
              'Decision Tree Method':dtc()}

    x_train, x_test, y_train, y_test = tts(x, y, test_size = 0.2, random_state = 42, shuffle = True, stratify = y)

    num_col = x_train.select_dtypes(include = ['int64', 'float64']).columns
    cat_col = x_train.select_dtypes(include = ['category', 'object']).columns

    prep = ct(transformers = [
        ('encoder', ohe(handle_unknown = 'ignore'), cat_col),
        ('scaler', ss(), num_col)])

    for name, model in models.items():
        print(f"\n{"="*7} {"*"*3} {name} {"*"*3} {"="*7}\n")

        pipe = Pipeline([
            ('preparation', prep),
            ('model', model)])
        pipe.fit(x_train, y_train)
        
        y_pred = pipe.predict(x_test)

        print(f"\nClssification Reports : {name}\n", cr(y_test, y_pred))

        c_matrix = cm(y_test, y_pred)
        TN, FP, FN, TP = c_matrix.ravel()
        print("Confusion Matrix :\n", c_matrix)
        print(f"TN\t: {TN} | {TN/(TN+FP+FN+TP)*100:.2f} %")
        print(f"FP\t: {FP} | {FP/(TP+FP+FN+TP)*100:.2f} %")
        print(f"FN\t: {FN} | {FN/(TN+FP+FN+TP)*100:.2f} %")
        print(f"TP\t: {TP} | {TP/(TN+FP+FN+TP)*100:.2f} %")


all_model_once(x, y)


======= *** Logistic Regression *** =======


Clssification Reports : Logistic Regression
               precision    recall  f1-score   support

          No       0.85      0.89      0.87      1035
         Yes       0.66      0.56      0.60       374

    accuracy                           0.81      1409
   macro avg       0.75      0.73      0.74      1409
weighted avg       0.80      0.81      0.80      1409

Confusion Matrix :
 [[926 109]
 [165 209]]
TN	: 926 | 65.72 %
FP	: 109 | 15.75 %
FN	: 165 | 11.71 %
TP	: 209 | 14.83 %

======= *** Support Vector Machine *** =======


Clssification Reports : Support Vector Machine
               precision    recall  f1-score   support

          No       0.83      0.90      0.86      1035
         Yes       0.64      0.48      0.55       374

    accuracy                           0.79      1409
   macro avg       0.74      0.69      0.71      1409
weighted avg       0.78      0.79      0.78      1409

Confusion Matrix :
 [[934 101]
 [193 